console.log("1)=====================================================================");
var givenStng=`     Hey you are doing good,keep it up      `;
console.log(givenStng);
console.log("2)=====================================================================");
var totalCount=givenStng.length;
console.log("length of the string is:",totalCount);
console.log("3)=====================================================================");
var result=givenStng.trim();
console.log("After removing leading and trailing extra spaces:",givenStng.trim());
console.log("4)=====================================================================");
var trimCount=result.length;
console.log("Total number of extra spaces count removed in step3 is:",totalCount-trimCount);
console.log("5)=====================================================================");
var lastChar=result.charAt(result.length-1);
console.log("First character after trim is:",result.charAt(0)  ,"   Last character after trim is:",lastChar);
console.log("6)=====================================================================");
console.log("Count of total words after 3rd step is:",result.length);
console.log("7)=====================================================================");
console.log(`Index of word "good" from given string is:`,givenStng.indexOf("good"));
console.log("8)=====================================================================");
console.log("Substrip starting from index 22 is ( by substring):", givenStng.substring(22));
console.log("Substrip starting from index 22 is ( by slice):", givenStng.slice(22));
console.log("9)=====================================================================");
console.log(`Is strind ends with word "up"?:`,result.endsWith("up"));
console.log("10)=====================================================================");
console.log(`Is strind starts with word "Hey"after trimming?:`,result.startsWith("Hey"));