console.log("================================================================");
var dreamComp= `My dream company is "Google"`;
console.log(dreamComp);
console.log("================================================================");
var myHobbies="My Hobbies are (before concat).............";
console.log(myHobbies);
var hobbyA="  Photography";
console.log(hobbyA);
var hobbyB="  Cooking";
console.log(hobbyB);
var hobbyC="  Planting";
console.log(hobbyC);
console.log("My Hobbies are (after concat)..............");
var result=hobbyA .concat( hobbyA, hobbyC);
console.log(result);
console.log("================================================================");